#pragma once

#define DRIVE_Y GetLeftY

#define SWITCHBOARD_PITMODE 0
#define SWITCHBOARD_LIMELIGHT_DISABLE 1
#define SWITCHBOARD_WRISTMOTOR_BROKEN 2
#define SWITCHBOARD_MANUALMODE 3
#define SWITCHBOARD_ID_4 4
#define SWITCHBOARD_ID_5 5
#define SWITCHBOARD_ID_6 6
#define SWITCHBOARD_ID_7 7
#define SWITCHBOARD_ID_8 8
#define SWITCHBOARD_ID_9 9
#define SWITCHBOARD_ID_10 10